const VALUE_KEY='constructionos_projects';
const CURRENCIES=[['INR','₹'],['USD','$'],['EUR','€'],['GBP','£'],['JPY','¥'],['AED','د.إ'],['SAR','﷼'],['CAD','C$'],['AUD','A$'],['SGD','S$']];
const rupees=n=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:0,maximumFractionDigits:2})}`;
const nativeSetter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;
function reactValue(input,value){nativeSetter.call(input,String(value));input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))}
function installValuePicker(){const form=document.querySelector('form.modal');if(!form||form.dataset.valueEnhanced)return;const inputs=[...form.querySelectorAll('input[type="number"]')];const valueInput=inputs.find(i=>i.placeholder==='25.5');if(!valueInput)return;form.dataset.valueEnhanced='1';const label=valueInput.closest('label');if(!label)return;const title=label.firstChild;if(title&&title.nodeType===3)title.textContent='Project value ';const row=document.createElement('div');row.className='value-unit-row';row.style.cssText='display:grid;grid-template-columns:1fr 115px;gap:8px;margin-top:7px';valueInput.style.marginTop='0';const select=document.createElement('select');select.setAttribute('aria-label','Project currency');select.style.cssText='height:43px;border:1px solid #d8e3df;border-radius:10px;padding:0 9px;background:#fff;color:#26332f;font-size:11px;outline:0';CURRENCIES.forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=`${t}  ${v}`;select.appendChild(o)});select.value='INR';const old=valueInput.parentNode;old.insertBefore(row,valueInput);row.appendChild(valueInput);row.appendChild(select);valueInput.dataset.currency='INR';select.addEventListener('change',()=>{valueInput.dataset.currency=select.value});form.addEventListener('submit',e=>{if(form.dataset.valueSubmitting==='1')return;e.preventDefault();e.stopImmediatePropagation();const amount=Number(valueInput.value||0);const currency=select.value;form.dataset.valueSubmitting='1';const currencyField=document.createElement('input');currencyField.type='hidden';currencyField.name='projectCurrency';currencyField.value=currency;form.appendChild(currencyField);reactValue(valueInput,amount);setTimeout(()=>form.requestSubmit(),0)},{capture:true})}
function patchMoneyText(){document.querySelectorAll('.project footer strong,.stat strong,.info-box strong,.cosx-card strong').forEach(el=>{const text=el.textContent.trim();const m=text.match(/^₹\s*([\d,.]+)\s*Cr$/);if(!m)return;const n=Number(m[1].replace(/,/g,''));if(Number.isFinite(n))el.textContent=rupees(n*1e7)})}
const style=document.createElement('style');style.textContent='.value-unit-row select:focus{border-color:#73bcb2;box-shadow:0 0 0 3px rgba(15,118,110,.08)}';document.head.appendChild(style);
const observer=new MutationObserver(()=>{installValuePicker();patchMoneyText()});observer.observe(document.body,{childList:true,subtree:true});
setInterval(()=>{installValuePicker();patchMoneyText()},800);
