const VALUE_KEY='constructionos_projects';
const UNITS=[['INR','₹'],['THOUSAND','Thousand'],['LAKH','Lakh'],['CRORE','Crore']];
const factor={INR:1,THOUSAND:1e3,LAKH:1e5,CRORE:1e7};
const rupees=n=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:0,maximumFractionDigits:2})}`;
const nativeSetter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;
function reactValue(input,value){nativeSetter.call(input,String(value));input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}
function installValuePicker(){const form=document.querySelector('form.modal');if(!form||form.dataset.valueEnhanced)return;const inputs=[...form.querySelectorAll('input[type="number"]')];const valueInput=inputs.find(i=>i.placeholder==='25.5');if(!valueInput)return;form.dataset.valueEnhanced='1';const label=valueInput.closest('label');if(!label)return;const title=label.firstChild;if(title&&title.nodeType===3)title.textContent='Project value ';const row=document.createElement('div');row.className='value-unit-row';row.style.cssText='display:grid;grid-template-columns:1fr 115px;gap:8px;margin-top:7px';valueInput.style.marginTop='0';const select=document.createElement('select');select.setAttribute('aria-label','Project value unit');select.style.cssText='height:43px;border:1px solid #d8e3df;border-radius:10px;padding:0 9px;background:#fff;color:#26332f;font-size:11px;outline:0';UNITS.forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;select.appendChild(o)});select.value='INR';const old=valueInput.parentNode;old.insertBefore(row,valueInput);row.appendChild(valueInput);row.appendChild(select);valueInput.dataset.valueUnit='INR';select.addEventListener('change',()=>{const from=valueInput.dataset.valueUnit||'INR';const current=Number(valueInput.value||0);const base=current*factor[from];reactValue(valueInput,base/factor[select.value]);valueInput.dataset.valueUnit=select.value});form.addEventListener('submit',e=>{if(form.dataset.valueSubmitting==='1')return;e.preventDefault();e.stopImmediatePropagation();const amount=Number(valueInput.value||0);const crore=(amount*factor[select.value])/1e7;form.dataset.valueSubmitting='1';reactValue(valueInput,crore);setTimeout(()=>form.requestSubmit(),0)},{capture:true})}
function patchMoneyText(){document.querySelectorAll('.project footer strong,.stat strong,.info-box strong,.cosx-card strong').forEach(el=>{const m=el.textContent.trim().match(/^₹\s*([\d,.]+)\s*Cr$/);if(!m)return;const n=Number(m[1].replace(/,/g,''));if(Number.isFinite(n))el.textContent=rupees(n*1e7)})}
const style=document.createElement('style');style.textContent='.value-unit-row select:focus{border-color:#73bcb2;box-shadow:0 0 0 3px rgba(15,118,110,.08)}';document.head.appendChild(style);
const observer=new MutationObserver(()=>{installValuePicker();patchMoneyText()});observer.observe(document.body,{childList:true,subtree:true});
setInterval(()=>{installValuePicker();patchMoneyText()},800);
